on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build CLI for OSx
        run: |
          make compile GOOS=darwin GOARCH=amd64
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Push Release
        uses: actions/upload-release-asset@v1
        id: upload_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./dist/b64-darwin-amd64.tgz
          asset_name: b64-darwin-amd64-${{ github.ref }}.tgz
          asset_content_type: application/gzip
      - name: Bump Formula
        uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: b64
          homebrew-tap: kdisneur/homebrew-formulae
          base-branch: master
          download-url: ${{ steps.upload_release.outputs.browser_download_url }}
          commit-message: "{{formulaName}} {{version}}"
        env:
          COMMITTER_TOKEN: ${{ secrets.MACHINE_USER }}
